version: '3.1'

services:

    db:
        # mysql/mysql-server is less in size than mysql
        image: mysql/mysql-server:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    wordpress:
        build:
            context: .
            args:
                WORDPRESS_DB_HOST: db:3306
                WORDPRESS_DB_NAME: wordpress
                WORDPRESS_DB_USER: wordpress
                WORDPRESS_DB_PASSWORD: wordpress
        ports:
            - "8080:80"
        depends_on:
            - db
        #volumes:
        #    # Mapping parent directory of the plugin to /src
        #    - .:/var/www/html
        restart: always
